name: setup

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build_devcontainer_image:
    # do this during a push to a branch (e.g. to main) or on a non-fork PR
    if: >
      github.event_name == 'push' ||
      (github.event.pull_request != null && github.event.pull_request.head.repo.full_name == github.repository)
    uses: ./.github/workflows/docker-image.yml
    with:
      image-name: ghcr.io/utoss/risc-v-ttgf-devcontainer
      dockerfile: .devcontainer/Dockerfile
      tag-prefix: ""
    secrets: inherit
